#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Registers a Windows Scheduled Task that triggers the StockPilot Pro
    automatic database backup job every night at 02:00.

.DESCRIPTION
    Writes a small runner script (run-backup.ps1) that calls
    POST /api/ops/backup/run with the BACKUP_JOB_SECRET header,
    then registers it as a SYSTEM scheduled task.
    If BACKUP_AUTO_RESTORE_ENABLED=true and BACKUP_RESTORE_TARGET_DATABASE_URL
    are configured on the API server, each backup run will also attempt
    pg_restore into that separate target database.

.PARAMETER ApiUrl
    Full URL of the backup trigger endpoint.
    Default: http://localhost:3000/api/ops/backup/run

.PARAMETER Secret
    Value of BACKUP_JOB_SECRET. Reads from the environment variable by default.

.PARAMETER RunTime
    Daily run time in HH:mm format. Default: 02:00

.EXAMPLE
    .\setup-backup-task.ps1
    .\setup-backup-task.ps1 -RunTime "03:30" -Secret "my-secret"
#>
param (
    [string]$ApiUrl  = 'http://localhost:3000/api/ops/backup/run',
    [string]$Secret  = $env:BACKUP_JOB_SECRET,
    [string]$RunTime = '02:00'
)

$TaskName    = 'StockPilotPro - Nightly Database Backup'
$ScriptsDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$RunnerPath  = Join-Path $ScriptsDir 'run-backup.ps1'

if (-not $Secret) {
    Write-Error 'BACKUP_JOB_SECRET is not set. Export it or pass -Secret "value".'
    exit 1
}

# ── Write the per-invocation runner script ────────────────────────────────────
@"
# Auto-generated by setup-backup-task.ps1 — do not edit manually.
# Re-run setup-backup-task.ps1 to update.
`$apiUrl = '$ApiUrl'
`$secret = '$Secret'

try {
    `$response = Invoke-RestMethod ``
        -Uri        `$apiUrl ``
        -Method     POST ``
        -Headers    @{ 'x-backup-job-secret' = `$secret } ``
        -ContentType 'application/json' ``
        -TimeoutSec  120

    if (`$response.data.success) {
        `$restoreInfo = ''
        if (`$response.data.restore -and `$response.data.restore.configured) {
            `$restoreState = if (`$response.data.restore.success) { 'OK' } else { 'FAILED' }
            `$restoreInfo = " | restore=`$restoreState target=`$(`$response.data.restore.targetHost)/`$(`$response.data.restore.targetDatabase)"
        }
        Write-Host "`$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') Backup OK — ``
`$(`$response.data.filePath) ``
(`$([math]::Round(`$response.data.sizeBytes / 1MB, 2)) MB, `$(`$response.data.durationMs) ms)`$restoreInfo"
    } else {
        Write-Error "`$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') Backup FAILED — `$(`$response.data.error)"
        exit 1
    }
} catch {
    Write-Error "`$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') Backup request failed — `$_"
    exit 1
}
"@ | Set-Content -Path $RunnerPath -Encoding UTF8

Write-Host "Runner script written to: $RunnerPath"

# ── Register the Scheduled Task ───────────────────────────────────────────────
$action    = New-ScheduledTaskAction `
    -Execute  'powershell.exe' `
    -Argument "-NonInteractive -NoProfile -WindowStyle Hidden -File `"$RunnerPath`""

$trigger   = New-ScheduledTaskTrigger -Daily -At $RunTime

$settings  = New-ScheduledTaskSettingsSet `
    -ExecutionTimeLimit (New-TimeSpan -Hours 1) `
    -RestartCount       3 `
    -RestartInterval    (New-TimeSpan -Minutes 10) `
    -StartWhenAvailable $true

$principal = New-ScheduledTaskPrincipal `
    -UserId    'SYSTEM' `
    -LogonType ServiceAccount `
    -RunLevel  Highest

# Remove previous registration if any
Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue

Register-ScheduledTask `
    -TaskName  $TaskName `
    -Action    $action `
    -Trigger   $trigger `
    -Settings  $settings `
    -Principal $principal | Out-Null

Write-Host ""
Write-Host "Scheduled task registered: '$TaskName'"
Write-Host "  Schedule : Daily at $RunTime"
Write-Host "  Runner   : $RunnerPath"
Write-Host ""
Write-Host "Useful commands:"
Write-Host "  Test now  : Start-ScheduledTask -TaskName '$TaskName'"
Write-Host "  Status    : Get-ScheduledTaskInfo -TaskName '$TaskName'"
Write-Host "  Remove    : Unregister-ScheduledTask -TaskName '$TaskName' -Confirm:`$false"
